# Generated by Django 5.1.5 on 2025-04-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='myAPI.person')),
            ],
        ),
    ]
